// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsp72h_fXxSPeXVYOGzWpGHYLTNU7F1DY',
    appId: '1:593834319057:web:a46bef9f6d4c52f9b439f0',
    messagingSenderId: '593834319057',
    projectId: 'redbus-wannabe',
    authDomain: 'redbus-wannabe.firebaseapp.com',
    storageBucket: 'redbus-wannabe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS_YmTSbBq4t5CNT_fNuwcoEvnkNrTM2w',
    appId: '1:593834319057:android:47e7a6a12a4e5565b439f0',
    messagingSenderId: '593834319057',
    projectId: 'redbus-wannabe',
    storageBucket: 'redbus-wannabe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPiz6XOqhem7uXO_A6LzRj6zLKii6evk',
    appId: '1:593834319057:ios:9f3031a9cff79890b439f0',
    messagingSenderId: '593834319057',
    projectId: 'redbus-wannabe',
    storageBucket: 'redbus-wannabe.firebasestorage.app',
    iosBundleId: 'com.example.redbusWannabe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtPiz6XOqhem7uXO_A6LzRj6zLKii6evk',
    appId: '1:593834319057:ios:9f3031a9cff79890b439f0',
    messagingSenderId: '593834319057',
    projectId: 'redbus-wannabe',
    storageBucket: 'redbus-wannabe.firebasestorage.app',
    iosBundleId: 'com.example.redbusWannabe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsp72h_fXxSPeXVYOGzWpGHYLTNU7F1DY',
    appId: '1:593834319057:web:8aac9ad6836f8e52b439f0',
    messagingSenderId: '593834319057',
    projectId: 'redbus-wannabe',
    authDomain: 'redbus-wannabe.firebaseapp.com',
    storageBucket: 'redbus-wannabe.firebasestorage.app',
  );
}
